### ISSUE TITLE
SyntaxError: f-string: unmatched '['

### ISSUE THREAD

**Issue by garon84** [NailAmber/MajorBot#2]
Traceback (most recent call last):
  File "C:\Users\manyuk.d\Downloads\bots\MajorBot\main.py", line 3, in <module>
    from utilities.starter import majorStart, majorStats
  File "C:\Users\manyuk.d\Downloads\bots\MajorBot\utilities\starter.py", line 1, in <module>
    from utilities.major import MajorBot
  File "C:\Users\manyuk.d\Downloads\bots\MajorBot\utilities\major.py", line 117
    logger.info(f"Major | Thread {self.thread} | {self.account} | Balance: {resp_json["data"]["user"]["gems"]}")
                                                                                       ^^^^
SyntaxError: f-string: unmatched '['
как победить ошибку?

**Comment by NailAmber** [comment]
Два варианта. Либо обновить python до последней версии, либо самому переписать момент с f строкой. Рекомендую обновить питон

**Comment by garon84** [comment]
Обновил до 3.12, все работает. Топ!

**Comment by Imaroubat** [comment]
Ошибка возникла в файле major.py на строке 110. Чтобы найти и исправить эту ошибку, откройте файл major.py и найдите строку, которая начинается с:
`logger.info(f"Major | Thread {self.thread} | {self.account} | Balance: {resp_json["data"]["user"]["gems"]}")`
Эту строку нужно заменить на:
`logger.info(f"Major | Thread {self.thread} | {self.account} | Balance: {resp_json['data']['user']['gems']}")`
Здесь я заменил внутренние двойные кавычки вокруг data и gems на одинарные. Это исправит ошибку синтаксиса, и ваш код должен работать корректно.

**Comment by Imaroubat** [comment]
```
if __name__ == '__main__':
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)

    loop.run_until_complete(main())
```
